---
- name: install apache2 on ununtu server
  hosts: dbservers
  become: true
  tasks:
  - name: install apache2
    apt:
      name: apache2
      state: present
    tags: install apache
  - name: start apache2
    service:
      name: apache2
      state: started
    
