---
- name: This sets up an httpd webserver
  hosts: webservers
  become: true  
  tasks:
    
  - name: install apache
    yum:
      name: httpd
      state: latest

  - name: star apache
    service:
      name: httpd
      state: stopped
